{% set name = "pymt_sedflux3d" %}
{% set version = "0.1" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - sedflux

  run:
    - python
    - setuptools
    - pymt
    - sedflux

test:
  requires:
    - bmi-tester
  imports:
    - pymt
    - sedflux3d
  commands:
    - mmd-stage Sedflux3d .
    - bmi-test sedflux3d:Sedflux3d --infile=sedflux_3d_init.kvf

about:
  summary: Python package that wraps the sedflux3d BMI.
  home: https://github.com/mcflugen/pymt_sedflux3d
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_sedflux3d
