build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries:
  - bmi_sedflux3d
  library_dirs: []
  undef_macros: []
info:
  github_username: mcflugen
  plugin_author: Eric Hutton
  plugin_license: MIT
  summary: PyMT plugin for sedflux3d
library:
  entry_point: Sedflux3D=sedflux3d:Sedflux3D
  language: c
  register: register_bmi_sedflux3d
plugin:
  name: sedflux3d
  requirements:
  - sedflux
