run_duration:
  description: Total model run time
  value:
    default: 36500.0
    range:
      min: 0.
      max: 1.79769313486e+308
    type: float
    units: d

bathymetry_method:
  description: Use a bathymetry with a linear shelf and slope
  value:
    choices: [linear, user]
    default: linear
    type: choice

bathymetry_file:
  description: CSV-formatted bathymetry file
  value:
    default: sedflux_3d_bathy.csv
    files:
      - sedflux_3d_bathy.csv
    type: file

shelf_gradient:
  description: Gradient of shelf
  value:
    default: 0.001
    range:
      max: 0.01
      min: 0.0
    type: float
    units: m

slope_gradient:
  description: Gradient of slope
  value:
    default: 0.01
    range:
      max: 0.1
      min: 0.0
    type: float
    units: m

shelf_width:
  description: Width of shelf
  value:
    default: 100000.0
    range:
      max: 1000000.0
      min: 1000.0
    type: float
    units: m

domain_width:
  description: Width of model domain
  value:
    default: 200000.0
    range:
      max: 10000000.0
      min: 0.0
    type: float
    units: m

sea_level_method:
  description: Use a linear rise/fall in sea level or user-defined
  value:
    choices:
      - linear
      - user
    default: linear
    type: choice

sea_level_file:
  description: CSV-formatted sea-level file
  value:
    default: sedflux_3d_sea_level.csv
    files:
      - sedflux_3d_sea_level.csv
    type: file

starting_sea_level_elevation:
  description: Sea level at simulation start
  value:
    default: 0.0
    range:
      max: 1000.0
      min: -1000.0
    type: float
    units: m

ending_sea_level_elevation:
  description: Sea level at simulation end
  value:
    default: 0.0
    range:
      max: 1000.0
      min: -1000.0
    type: float
    units: m
  description: Grid

z_resolution:
  description: Resolution in the vertical direction
  value:
    default: 0.5
    range:
      max: 10.0
      min: 0.01
    type: float
    units: m

x_resolution:
  description: Grid resolution in the x-direction
  value:
    default: 500.0
    range:
      max: 1.79769313486e+308
      min: 0
    type: float
    units: m

y_resolution:
  description: Grid resolution in the y-direction
  value:
    default: 500.0
    range:
      max: 1.79769313486e+308
      min: 0.0
    type: float
    units: m

compaction_process_is_on:
  description: Turn on/off the compaction process module
  value:
    choices: [yes, no]
    default: no
    type: choice

isostasy_process_is_on:
  description: Turn on/off the isostasy process module
  value:
    choices: [yes, no]
    default: no
    type: choice

isostasy_effective_elastic_thickness:
  description: Effective elastic thickness of crust
  value:
    default: 65000.0
    range:
      max: 1.79769313486e+308
      min: 1000.0
    type: float
    units: m

isostasy_youngs_modulus:
  description: Youngs modulus
  value:
    default: 70000000000.0
    range:
      max: 1000000000000.0
      min: 1000000000.0
    type: float
    units: Pa

isostasy_relaxation_time:
  description: Relaxation time of crust
  name: Relaxation time
  value:
    default: 5000.0
    range:
      max: 100000.0
      min: 0.0
    type: float
    units: Pa

river_bed_load_flux:
  description: Bed-load flux at river mouth
  value:
    default: 70.0
    range:
      max: 1000.0
      min: 0.01
    type: float
    units: kg/s

river_suspended_load_concentration_0:
  description: Suspended load concentration of grain class 0
  value:
    default: 0.1
    range:
      max: 1.0
      min: 0.01
    type: float
    units: kg/m^3

river_suspended_load_concentration_1:
  description: Suspended load concentration of grain class 1
  value:
    default: 0.1
    range:
      max: 1.0
      min: 0.01
    type: float
    units: kg/m^3

river_velocity:
  description: Flow velocity at river mouth
  value:
    default: 1.2
    range:
      max: 5.0
      min: 0.5
    type: float
    units: m/s

river_width:
  description: Width of river at river mouth
  value:
    default: 400.0
    range:
      max: 5000.0
      min: 10.0
    type: float
    units: m

river_depth:
  description: Depth of river at river mouth
  value:
    default: 4.0
    range:
      max: 50.0
      min: 1.0
    type: float
    units: m

bed_load_dump_length:
  description: Distance from the river mouth over which to dump bed load
  value:
    default: 2000.0
    range:
      max: 10000.0
      min: 10.0
    type: float
    units: m

plume_max_width:
  description: Maximum width of the river plume
  value:
    default: 15.0
    range:
      max: 100.0
      min: 1.0
    type: float
    units: km

plume_cross_shore_nodes:
  description:
    Number of nodes in the cross-shore direction of the plume solution grid
    (must be odd)
  value:
    default: 21
    range:
      max: 21
      min: 3
    type: int
    units: "-"

plume_river_mouth_nodes:
  description:
    Number of nodes within the river mouth of the plume solution grid (must
    be odd)
  value:
    default: 3
    range:
      max: 21
      min: 3
    type: int
    units: "-"

bed_load_sediment_grain_size:
  description: Grain size of bed-load sediment
  value:
    default: 400.0
    range:
      max: 5000.0
      min: 0.1
    type: float
    units: um

bed_load_sediment_grain_density:
  description: Grain density of bed-load sediment
  value:
    default: 2625.0
    range:
      max: 2650.0
      min: 1000.0
    type: float
    units: kg m^-3

bed_load_sediment_saturated_density:
  description: Saturated bulk-density of bed-load sediment
  value:
    default: 1850.0
    range:
      max: 2650.0
      min: 1000.0
    type: float
    units: kg m^-3

bed_load_sediment_minimum_void_ratio:
  description: Void ratio of bed-load sediment in closest-packed state
  value:
    default: 0.3
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"

bed_load_sediment_diffusion_coefficient:
  description: Diffusion coefficient of bed-load sediment
  value:
    default: 0.25
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"

suspended_load_sediment_1_grain_size:
  description: Grain size of suspended-load sediment class 1
  value:
    default: 150.0
    range:
      max: 5000.0
      min: 0.1
    type: float
    units: um

suspended_load_sediment_2_grain_size:
  description: Grain size of suspended-load sediment class 2
  value:
    default: 50.0
    range:
      max: 5000.0
      min: 0.1
    type: float
    units: um

suspended_load_sediment_1_grain_density:
  description: Grain density of suspended-load sediment class 1
  value:
    default: 2600.0
    range:
      max: 2650.0
      min: 1000.0
    type: float
    units: kg m^-3

suspended_load_sediment_2_grain_density:
  description: Grain density of suspended-load sediment class 2
  value:
    default: 2400.0
    range:
      max: 2650.0
      min: 1000.0
    type: float
    units: kg m^-3

suspended_load_sediment_1_saturated_density:
  description: Saturated bulk-density of suspended-load sediment class 1
  value:
    default: 1800.0
    range:
      max: 2650.0
      min: 1000.0
    type: float
    units: kg m^-3

suspended_load_sediment_2_saturated_density:
  description: Saturated bulk-density of suspended-load sediment class 2
  value:
    default: 1600.0
    range:
      max: 2650.0
      min: 1000.0
    type: float
    units: kg m^-3

suspended_load_sediment_1_minimum_void_ratio:
  description:
    Void ratio of suspended-load sediment class 1 in closest-packed state
  value:
    default: 0.2
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"

suspended_load_sediment_2_minimum_void_ratio:
  description:
    Void ratio of suspended-load sediment class 2 in closest-packed state
  value:
    default: 0.1
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"

suspended_load_sediment_1_diffusion_coefficient:
  description: Diffusion coefficient of suspended-load sediment class 1
  value:
    default: 0.25
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"

suspended_load_sediment_2_diffusion_coefficient:
  description: Diffusion coefficient of suspended-load sediment class 2
  value:
    default: 0.25
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"

suspended_load_sediment_1_removal_rate:
  description: Removal rate of suspended-load sediment class 1
  value:
    default: 16.8
    range:
      max: 100.0
      min: 0.1
    type: float
    units: d^-1

suspended_load_sediment_2_removal_rate:
  description: Removal rate of suspended-load sediment class 2
  value:
    default: 1.0
    range:
      max: 100.0
      min: 0.1
    type: float
    units: d^-1
